version: "3.9"
services:
    web:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - LAPTOP-99V1MP1F
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "1234"
            ACCEPT_EULA: "Y"